//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forecast
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecast
    {
        public int Id { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> MinTemp { get; set; }
        public Nullable<int> MaxTemp { get; set; }
        public Nullable<int> Precip { get; set; }
        public Nullable<int> Humidity { get; set; }
        public Nullable<int> WindSpeed { get; set; }
    }
}
